$('.owl-carousel').owlCarousel({
    loop:true,
    margin:1,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        768:{
            items:3,
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        }
    }
})